export const characterIds: Record<number, string> = {
  0: "Captain Falcon",
  1: "Donkey Kong",
  2: "Fox",
  3: "Mr. Game & Watch",
  4: "Kirby",
  5: "Bowser",
  6: "Link",
  7: "Luigi",
  8: "Mario",
  9: "Marth",
  10: "Mewtwo",
  11: "Ness",
  12: "Peach",
  13: "Pikachu",
  14: "Ice Climbers",
  15: "Jigglypuff",
  16: "Samus",
  17: "Yoshi",
  18: "Zelda",
  19: "Sheik",
  20: "Falco",
  21: "Young Link",
  22: "Dr. Mario",
  23: "Roy",
  24: "Pichu",
  25: "Ganondorf",
  26: "Master Hand",
  27: "Wireframe Male",
  28: "Wireframe Female",
  29: "Giga Bowser",
  30: "Crazy Hand",
  31: "Sandbag",
  32: "Popo",
};

export const stageIds: Record<number, string> = {
  0: "Dummy",
  1: "TEST",
  2: "Fountain of Dreams",
  3: "Pokémon Stadium",
  4: "Princess Peach's Castle",
  5: "Kongo Jungle",
  6: "Brinstar",
  7: "Corneria",
  8: "Yoshi's Story",
  9: "Onett",
  10: "Mute City",
  11: "Rainbow Cruise",
  12: "Jungle Japes",
  13: "Great Bay",
  14: "Hyrule Temple",
  15: "Brinstar Depths",
  16: "Yoshi's Island",
  17: "Green Greens",
  18: "Fourside",
  19: "Mushroom Kingdom I",
  20: "Mushroom Kingdom II",
  21: "Akaneia",
  22: "Venom",
  23: "Poké Floats",
  24: "Big Blue",
  25: "Icicle Mountain",
  26: "Icetop",
  27: "Flatzone",
  28: "Dream Land N64",
  29: "Yoshi's Island N64",
  30: "Battlefield",
  31: "Final Destination",
};
