CREATE TABLE "account" (
	"id" text PRIMARY KEY NOT NULL,
	"account_id" text NOT NULL,
	"provider_id" text NOT NULL,
	"user_id" text NOT NULL,
	"access_token" text,
	"refresh_token" text,
	"id_token" text,
	"access_token_expires_at" timestamp,
	"refresh_token_expires_at" timestamp,
	"scope" text,
	"password" text,
	"created_at" timestamp NOT NULL,
	"updated_at" timestamp NOT NULL
);
--> statement-breakpoint
CREATE TABLE "passkey" (
	"id" text PRIMARY KEY NOT NULL,
	"name" text,
	"public_key" text NOT NULL,
	"user_id" text NOT NULL,
	"credential_i_d" text NOT NULL,
	"counter" integer NOT NULL,
	"device_type" text NOT NULL,
	"backed_up" boolean NOT NULL,
	"transports" text,
	"created_at" timestamp
);
--> statement-breakpoint
CREATE TABLE "session" (
	"id" text PRIMARY KEY NOT NULL,
	"expires_at" timestamp NOT NULL,
	"token" text NOT NULL,
	"created_at" timestamp NOT NULL,
	"updated_at" timestamp NOT NULL,
	"ip_address" text,
	"user_agent" text,
	"user_id" text NOT NULL,
	"impersonated_by" text,
	CONSTRAINT "session_token_unique" UNIQUE("token")
);
--> statement-breakpoint
CREATE TABLE "user" (
	"id" text PRIMARY KEY NOT NULL,
	"name" text NOT NULL,
	"email" text NOT NULL,
	"email_verified" boolean NOT NULL,
	"image" text,
	"created_at" timestamp NOT NULL,
	"updated_at" timestamp NOT NULL,
	"role" text,
	"banned" boolean,
	"ban_reason" text,
	"ban_expires" timestamp,
	CONSTRAINT "user_email_unique" UNIQUE("email")
);
--> statement-breakpoint
CREATE TABLE "verification" (
	"id" text PRIMARY KEY NOT NULL,
	"identifier" text NOT NULL,
	"value" text NOT NULL,
	"expires_at" timestamp NOT NULL,
	"created_at" timestamp,
	"updated_at" timestamp
);
--> statement-breakpoint
CREATE TABLE "collector" (
	"uid" text PRIMARY KEY NOT NULL,
	"display_name" text NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone,
	"token" text NOT NULL,
	"token_expires_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "replay" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "replay_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"key" text NOT NULL,
	"updated_at" timestamp with time zone,
	"started_at" timestamp with time zone NOT NULL,
	"frame_count" integer,
	"stage_id" integer,
	"character_ids" integer[] NOT NULL,
	"file_url" text,
	"is_finished" boolean DEFAULT false NOT NULL,
	"collector_uid" text NOT NULL,
	CONSTRAINT "character_ids_length" CHECK (array_length("replay"."character_ids", 1) = 2)
);
--> statement-breakpoint
CREATE TABLE "wii" (
	"mac_address" text PRIMARY KEY NOT NULL,
	"nickname" text NOT NULL,
	"ip_address" text NOT NULL,
	"collector_uid" text NOT NULL,
	CONSTRAINT "ip_address_is_valid" CHECK ("wii"."ip_address" ~* '^(?:[0-9]{1,3}.){3}[0-9]{1,3}$'),
	CONSTRAINT "mac_address_is_valid" CHECK ("wii"."mac_address" ~* '^([0-9A-Fa-f]{2}:){5}([0-9A-Fa-f]{2})$')
);
--> statement-breakpoint
ALTER TABLE "account" ADD CONSTRAINT "account_user_id_user_id_fk" FOREIGN KEY ("user_id") REFERENCES "public"."user"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "passkey" ADD CONSTRAINT "passkey_user_id_user_id_fk" FOREIGN KEY ("user_id") REFERENCES "public"."user"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "session" ADD CONSTRAINT "session_user_id_user_id_fk" FOREIGN KEY ("user_id") REFERENCES "public"."user"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "replay" ADD CONSTRAINT "replay_collector_uid_collector_uid_fk" FOREIGN KEY ("collector_uid") REFERENCES "public"."collector"("uid") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "wii" ADD CONSTRAINT "wii_collector_uid_collector_uid_fk" FOREIGN KEY ("collector_uid") REFERENCES "public"."collector"("uid") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
CREATE INDEX "key_idx" ON "replay" USING btree ("key");--> statement-breakpoint
CREATE INDEX "collector_uid_idx" ON "wii" USING btree ("collector_uid");